- name: Create local share if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_share }}"
    state: directory
    recurse: yes

# @NOTE
# - This is the ONLY time we symlink
- name: Create symlink to nap directory 
  file:
    src: "{{ role_path }}/files"
    dest: "{{ local_share }}/nap"
    state: link
