- name: List existing vcsh configs
  shell: "{{ vendor_bin }}/vcsh list" 
  register: vcsh_list

# If it doesn't exist clone
- name: Clone snippets config using vcsh
  command: "{{ vendor_bin }}/vcsh clone -b snippets {{ git_repo }} snippets"
  when: not vcsh_list.stdout is search("snippets")

# If it already exists pull
- name: Pull snippets config using vcsh
  command: "{{ vendor_bin }}/vcsh snippets pull"
  when: vcsh_list.stdout is search("snippets")

