# Snippets config
nap_default_extension: ts

# Themes
theme_nap: catppuccin-mocha
theme_bat: Catppuccin-mocha
theme_helix: tokyonight
theme_glamour: mocha.json
theme_wezterm: "tokyonight"

# Colors

# - Based off of Helix theme line numbers
color_wezterm_tabs_active: "#B4BEFE"
color_wezterm_tabs_inactive: "#45475A"
color_wezterm_tabs_background: "#1E1E2E"
