- name: Create Helix config direcotry
  file:
    path: "{{ config_dir }}/helix"
    state: directory
    recurse: yes
    mode: "0755"

- name: Copy Helix config template directories
  file:
    dest: "{{ config_dir }}/helix/{{ item.path }}"
    mode: "0755"
    state: directory
  with_filetree: "../templates"
  when: item.state == "directory"

- name: Copy Helix config template files
  template:
    src: "{{ item.src }}"
    dest: "{{ config_dir }}/helix/{{ item.path }}"
    mode: "0644"
  with_filetree: "../templates"
  when: item.state == "file"

- name: Synchronize Helix config files
  ansible.posix.synchronize:
    src: ../files/
    dest: "{{ config_dir }}/helix"

