# This does technically download every time...
# - But seeing as it goes to `/tmp/` it gets wiped anyway
- name: Download sheldon linux install script on openSUSE
  get_url:
    url: https://rossmacarthur.github.io/install/crate.sh
    mode: 0755
    dest: /tmp/crate.sh

- name: Create local bin if it doesn't exist
  file:
    mode: 0755
    path: "{{ local_bin }}"
    state: directory
    recurse: yes

- name: Run sheldon linux install script on openSUSE
  command:
    cmd: "/tmp/crate.sh --force --repo rossmacarthur/sheldon --to {{ local_bin }}"
    creates: "{{ local_bin }}/sheldon"