
- name: Create Sheldon config direcotry
  file:
    path: "{{ config_dir }}/sheldon"
    state: directory
    recurse: yes
    mode: "0755"

- name: Synchronize Sheldon config files
  ansible.posix.synchronize:
    src: ../files/
    dest: "{{ config_dir }}/sheldon"

